package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"habit-streak-tracker/internal/graph/generated"
	"habit-streak-tracker/internal/models"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, name string, email string, password string) (*models.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*models.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, name *string, email *string, password *string) (*models.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// CreateHabit is the resolver for the createHabit field.
func (r *mutationResolver) CreateHabit(ctx context.Context, name string, description string) (*models.Habit, error) {
	panic(fmt.Errorf("not implemented: CreateHabit - createHabit"))
}

// UpdateHabit is the resolver for the updateHabit field.
func (r *mutationResolver) UpdateHabit(ctx context.Context, id string, name *string, description *string) (*models.Habit, error) {
	panic(fmt.Errorf("not implemented: UpdateHabit - updateHabit"))
}

// DeleteHabit is the resolver for the deleteHabit field.
func (r *mutationResolver) DeleteHabit(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteHabit - deleteHabit"))
}

// CheckInHabit is the resolver for the checkInHabit field.
func (r *mutationResolver) CheckInHabit(ctx context.Context, habitID string, date *string) (*models.HabitLog, error) {
	panic(fmt.Errorf("not implemented: CheckInHabit - checkInHabit"))
}

// DeleteHabitLog is the resolver for the deleteHabitLog field.
func (r *mutationResolver) DeleteHabitLog(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteHabitLog - deleteHabitLog"))
}

// Habits is the resolver for the habits field.
func (r *queryResolver) Habits(ctx context.Context) ([]*models.Habit, error) {
	panic(fmt.Errorf("not implemented: Habits - habits"))
}

// Habit is the resolver for the habit field.
func (r *queryResolver) Habit(ctx context.Context, id string) (*models.Habit, error) {
	panic(fmt.Errorf("not implemented: Habit - habit"))
}

// HabitLogs is the resolver for the habitLogs field.
func (r *queryResolver) HabitLogs(ctx context.Context, habitID string) ([]*models.HabitLog, error) {
	panic(fmt.Errorf("not implemented: HabitLogs - habitLogs"))
}

// Habit returns generated.HabitResolver implementation.
func (r *Resolver) Habit() generated.HabitResolver { return &habitResolver{r} }

// HabitLog returns generated.HabitLogResolver implementation.
func (r *Resolver) HabitLog() generated.HabitLogResolver { return &habitLogResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	habitResolver    struct{ *Resolver }
	habitLogResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
