package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"habit-streak-tracker/internal/graph/generated"
	"habit-streak-tracker/internal/models"
)

// UpdateHabit is the resolver for the updateHabit field.
func (r *mutationResolver) UpdateHabit(ctx context.Context, id string, name *string, description *string) (*models.Habit, error) {
	panic(fmt.Errorf("not implemented: UpdateHabit - updateHabit"))
}

// DeleteHabit is the resolver for the deleteHabit field.
func (r *mutationResolver) DeleteHabit(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteHabit - deleteHabit"))
}

// CheckInHabit is the resolver for the checkInHabit field.
func (r *mutationResolver) CheckInHabit(ctx context.Context, habitID string, date *string) (*models.HabitLog, error) {
	panic(fmt.Errorf("not implemented: CheckInHabit - checkInHabit"))
}

// DeleteHabitLog is the resolver for the deleteHabitLog field.
func (r *mutationResolver) DeleteHabitLog(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteHabitLog - deleteHabitLog"))
}

// Habit returns generated.HabitResolver implementation.
func (r *Resolver) Habit() generated.HabitResolver { return &habitResolver{r} }

// HabitLog returns generated.HabitLogResolver implementation.
func (r *Resolver) HabitLog() generated.HabitLogResolver { return &habitLogResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	habitResolver    struct{ *Resolver }
	habitLogResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
