package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"habit-streak-tracker/internal/graph/generated"
)

// Habit returns generated.HabitResolver implementation.
func (r *Resolver) Habit() generated.HabitResolver { return &habitResolver{r} }

// HabitLog returns generated.HabitLogResolver implementation.
func (r *Resolver) HabitLog() generated.HabitLogResolver { return &habitLogResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	habitResolver    struct{ *Resolver }
	habitLogResolver struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
